app: 
  name: fetch
  context: ${app.name}-prj

server: 
  port: 30001
  servlet: 
    context-path: /${app.context}
  jsp-servlet: 
    init-parameters: 
      development: true 

logging: 
  config: classpath:logback-spring.xml  

spring: 
  aop: 
    proxy-target-class: true #此项配置很重要，强行使用CGLib的代理方式

  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    #&useSSL=false 标识不使用ssl链接，屏蔽warn警告
    url: jdbc:mysql://127.0.0.1:3306/syk?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    filters: mergeStat
    initialSize: 1
    maxActive: 20
    minIdle: 1
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxOpenPreparedStatements: 20
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    
  redis: 
    database: 0  #根据环境更换库
    host: 127.0.0.1
    port: 6379
    timeout: 20000  #连接超时时间（毫秒）
    pool: 
      max-active: 8  #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8  #连接池中的最大空闲连接
      min-idle: 0  #连接池中的最小空闲连接
 
  mvc: 
    view: 
      prefix: /qzsoft/

  http: 
    multipart: 
      maxFileSize: 100Mb
      maxRequestSize: 100Mb
      
  threadpool: 
    corePoolSize: 5
    maxPoolSize: 15
    queueCapacity: 15
    allowCoreThreadTimeOut: true
      
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.sbolo.syk.*.po
